# application name should be "eureka-service" and should start at 8761
server:
  port: 8761

spring:
  application:
    name: eureka-service
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false