# application name should be "api-gateway" and the application configuration should
# be retrieved from "http://localhost:8888"

server:
   port: 8090
spring:
  application:
    name: api-gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    sbservice-one:
      serviceId: sbservice-one
    sbservice-two:
      serviceId: sbservice-two

#zuul:
#  routes:
#    sbservice-one:
#      path: http://localhost:8081