# application name should be "sbservice-one" and the application configuration should
# be retrieved from "http://localhost:8888"
server:
   port: 8081
spring:
  application:
    name: sbservice-one
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

app:
  message: Hello !!! Message from SpringBoot Service One !!!